from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.imgLabel.sizePolicy().hasHeightForWidth())
        self.imgLabel.setSizePolicy(sizePolicy)
        self.imgLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgLabel.setLineWidth(6)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.verticalLayout.addWidget(self.imgLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CAPTURE = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CAPTURE.sizePolicy().hasHeightForWidth())
        self.CAPTURE.setSizePolicy(sizePolicy)
        self.CAPTURE.setMinimumSize(QtCore.QSize(0, 0))
        self.CAPTURE.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.CAPTURE.setObjectName("CAPTURE")
        self.horizontalLayout.addWidget(self.CAPTURE)
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Exit.sizePolicy().hasHeightForWidth())
        self.Exit.setSizePolicy(sizePolicy)
        self.Exit.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.Exit.setObjectName("Exit")
        self.horizontalLayout.addWidget(self.Exit)
        self.SHOW = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SHOW.sizePolicy().hasHeightForWidth())
        self.SHOW.setSizePolicy(sizePolicy)
        self.SHOW.setMinimumSize(QtCore.QSize(0, 0))
        self.SHOW.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.SHOW.setIconSize(QtCore.QSize(16, 16))
        self.SHOW.setObjectName("SHOW")
        self.horizontalLayout.addWidget(self.SHOW)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CAPTURE.setText(_translate("MainWindow", "Ekran Resmi Al"))
        self.Exit.setText(_translate("MainWindow", "İşlemi Sonlandır"))
        self.SHOW.setText(_translate("MainWindow", "Görüntü İşle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

